FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /src

COPY ["Inventario.Api/Inventario.Api.csproj", "Inventario.Api/"]

RUN dotnet restore "Inventario.Api/Inventario.Api.csproj"

COPY . .

WORKDIR /src/Inventario.Api

RUN dotnet tool install --global dotnet-ef --version 8.0.19

ENV PATH="${PATH}:/root/.dotnet/tools"

ENTRYPOINT ["dotnet", "ef", "database", "update"]