services:

  postgres:
    image: postgres:16
    container_name: inventario-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: inventario
      POSTGRES_USER: inventario
      POSTGRES_PASSWORD: inventario_dev

    ports:
      - "5433:5432"

    volumes:
      - inventario_postgres_data:/var/lib/postgresql/data


  api:
    image: inventario-api
    container_name: inventario-api
    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=inventario;Username=inventario;Password=inventario_dev

    depends_on:
      - postgres


volumes:
  inventario_postgres_data: